services:
  - type: web
    name: lmk-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --pythonpath .
    envVars:
      - key: LMK_ADMIN_KEY
        value: lmk-admin-2026
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY_FRANKLIN
        sync: false
